# Generated by Django 5.1.6 on 2025-03-03 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoMarkModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.CharField(max_length=100, verbose_name='Марка')),
                ('model', models.CharField(max_length=100, verbose_name='Модель')),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Наименование')),
                ('price', models.FloatField(verbose_name='Цена')),
            ],
        ),
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gos_num', models.CharField(max_length=9, verbose_name='Гос. номер')),
                ('vin_num', models.CharField(max_length=17, verbose_name='VIN номер')),
                ('engine_num', models.CharField(max_length=50, verbose_name='Серия и номер двигателя')),
                ('released_year', models.IntegerField(max_length=4, verbose_name='Год изготовления')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('mark_model', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='webapp.automarkmodel', verbose_name='Марка и модель')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(verbose_name='Дата и время записи')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('info', models.CharField(blank=True, max_length=200, null=True, verbose_name='Доп. информация')),
                ('worker', models.CharField(max_length=200, verbose_name='Работник')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания заявки')),
                ('auto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.auto', verbose_name='Автомобиль')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('service', models.ManyToManyField(to='webapp.services', verbose_name='Услуга')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=200, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
