# Generated by Django 5.1.6 on 2025-05-29 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100, verbose_name='Модель')),
            ],
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.CharField(max_length=100, verbose_name='Марка')),
                ('logo', models.ImageField(upload_to='logo_auto', verbose_name='Логотип')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
            ],
            options={
                'verbose_name': 'Категория услуг',
                'verbose_name_plural': 'Категории услуг',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gos_num', models.CharField(max_length=9, unique=True, verbose_name='Гос. номер')),
                ('vin_num', models.CharField(max_length=17, unique=True, verbose_name='VIN номер')),
                ('engine_num', models.CharField(max_length=50, verbose_name='Серия двигателя')),
                ('released_year', models.IntegerField(max_length=4, verbose_name='Год изготовления')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('mark_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.automodel', verbose_name='Марка и модель')),
            ],
        ),
        migrations.AddField(
            model_name='automodel',
            name='mark',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.mark', verbose_name='Марка'),
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('datetime', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Наименование')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='webapp.servicecategory', verbose_name='Категория')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(blank=True, max_length=200, null=True, verbose_name='ФИО')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('gos_num', models.CharField(blank=True, max_length=9, null=True, verbose_name='Гос. номер')),
                ('datetime', models.DateTimeField(verbose_name='Дата и время записи')),
                ('comment', models.CharField(blank=True, max_length=200, null=True, verbose_name='Комментарий')),
                ('info', models.CharField(blank=True, max_length=200, null=True, verbose_name='Доп. информация')),
                ('worker', models.CharField(blank=True, max_length=200, null=True, verbose_name='Работник')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания заявки')),
                ('status', models.CharField(choices=[('0', 'Новая'), ('1', 'Ожидание'), ('2', 'Согласование'), ('3', 'В работе'), ('4', 'Готово'), ('5', 'Выдано'), ('6', 'Отменена')], default='0', max_length=1, verbose_name='Статус')),
                ('reason', models.CharField(blank=True, max_length=200, null=True, verbose_name='Причина отмены')),
                ('auto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.auto', verbose_name='Автомобиль')),
                ('car_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.automodel', verbose_name='Модель')),
                ('mark', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.mark', verbose_name='Марка')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('service', models.ManyToManyField(to='webapp.services', verbose_name='Услуга')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=200, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
